### ISSUE TITLE
[Risk: Informational] redundant code

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#10]
1. The whole [debug file](https://github.com/battlehard/hardened/blob/main/src/Hardened/Hardened.Debug.cs) could be deleted before compiling the release version.

2. [`ContainsValue`](https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Helpers.cs#L58) could be deleted before release.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.cs#L71-L105

3. The NFT's transfer-in logic are common path for all the conditions. It's recommended to write it only once for conciseness.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L77

4. `pending.bhNftId` could be checked by the `IsEmpty` defined in the `Helper` part.

5. The `Common/Extension.cs` could be deleted. 

* `AddressToScriptHash` could be avoided by avoid using the `Address`. The frontend part could do the conversions for the GAS Saving. 
* `HexStringToUInt160` could also be avoided by avoid using the `HexString`. The frontend part could do this.
* Concat could be move to the `Hardend.Helpers.cs`. For future development, if the array's length is very long, it's recommended to use `Unpack` and `Pack` opcodes directly instead of pushing them to a new array one by one.

6.  The `Common/Helpers.cs` could be merged to `Hardend.Helpers.cs`.

* `Assert` could be replace by `ExecutionEngine.Assert`
* `GenerateUuidV4`, `BytesToHexString`, `GetHexChar`, `IsUuid`, `IsHexChar` could be deleted

7.  The `Common/Transfer.cs` could be merged to `Hardend.Helpers.cs`. What's more, in both `Safe11Transfer` and `Safe17Transfer`, the try-catch statement could be deleted safely and keep only the internal part of the `try` statement.

**Comment by RawichK** [comment]
@overlordsecurity There was a discussion around ExecutionEngine.Assert where it does not throw an Exception and may introduce exploitation where the attacker tries to trick the contract just to pass the Assertion and execute the next steps.
This vulnerability was solved already?

**Comment by digimbyte** [comment]
Can you find a reference or a snapshot of this exploit or discussion for @overlordsecurity?

**Comment by RawichK** [comment]
It was the other way around. Exception should not be used in the public method because it can be intercepted and bypassed.
So, the best practice back then was to use ExecutionEngine.Assert. 
However, it has a drawback, when Assert fails, there will be no error message thrown back to the caller. Which means that the frontend web app cannot show an appropriate message to user.
However, the vulnerability was solved with compiler version 3.3.1.0, that's why we use exception instead of ExecutionEngine.Assert. That's why we decided to use Exception which wrapped in internal `Assert` method as you see in the code.

@overlordsecurity Any ideas or comments on this kind of usage?
![image](https://github.com/battlehard/hardened/assets/8307015/152b4b2d-6a77-4d34-9714-c5eeb67e0736)
![image](https://github.com/battlehard/hardened/assets/8307015/09497409-e57d-4b96-a966-1c6285126039)

**Comment by overlordsecurity** [comment]
You're right about this. Some rpc providers would give a better information for exceptions `throwed` by the contract. If these messges were meant to be passed to users through front-end, then let's keep this way. The safety is the same for both ways and the GAS cost is basically the same.

**Comment by overlordsecurity** [comment]
> Can you find a reference or a snapshot of this exploit or discussion for @overlordsecurity?

https://github.com/neo-project/neo/pull/2729 This pr has fixed the issue mentioned in No.7. Therefore, we don't need to copy code from flamingo-finance anymore.
