### ISSUE TITLE
[Risk: Low] lack of validity checks

### ISSUE THREAD

**Issue by overlordsecurity** [battlehard/hardened#8]
In hardened project, there exist some functions lack of validity checks.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L39-L43

It's recommended to perform `ValidateScriptHash` for `contractHash`.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L57-L65

It's recommended to perform valid range checks for the non-null parameters such as positive-test for `gasMintCost`.

https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L79
https://github.com/battlehard/hardened/blob/f196c00db22811d6d9660cfc9f714f54f32bb6b5/src/Hardened/Hardened.Admin.cs#L120

It's recommended to perform checks to `payTokenHash` and `payTokenAmount` in `InfusionUpdate` like what the `InfusionMint` done.
> It's unknown to the **overlord team** that if this is a problem or not because lack of documents. Please take a look. In `InfusionMint`, `payToken` is transferred to the `contractHash` provided by `admin`. While in `InfusionUpdate`, it's transferred to `walletPoolHash`.

**Comment by digimbyte** [comment]
This is an oversight, configured contracts have a dedicated "pool" to send tokens to as part of the recycling system. This should always be relevant to the BH context. They should be the same destination on a per context basis (official or BlackMarket) 

Example:
TTM BHs should send to TTM wallet pool
BlackMarket BHs should go to BH wallet pool

A) 
All official configured contracts should have a known destination for their wallet pools, so if we use a validation on the contract side, the contract owner needs to define it on that nft.

B) 
Otherwise we use our internal server database once we've validated the user to represent that contract

----
Personally I am open to both options, but I do want a balance of security and convenience for contract owners.

If we can validate the contract owner, we can mint an Nft or use storage to persist contract configuration

**Comment by digimbyte** [comment]
would love some feedback and suggestions on this that makes a secure and consistent design pattern.
the goal is to authorize a wallet user as a manager/owner of another contract and allow them to define config options.

such as;
- destination for tokens on mint and update methods.
- setting the cost for mint and update methods

perhaps some additional methods are needed for a full cycle with the client/server/contract.

**Comment by RawichK** [comment]
There are no standards for validating the contract owner as we discussed with NEO community earlier, that's why we decided to transfer `payToken` to the `contractHash` provided by `admin` as option B instead.
So this is a bug that `InfusionUpdate` transfer `payToken` to the pool instead of `contractHash` provided by `admin`

--- 
Separate discussion with @digimbyte 
What is the logic to define whether a BH NFT is TTM BH, Blackmarket BH, Humswap BH, and so on?

**Comment by digimbyte** [comment]
Isn't this just an issue of two methods (mint vs update) having different handling of the pay token destination? 
they should be the same based on the pool destination from the server.

----
as for the 'branding' of official vs not official, its normally handled by the server. to have that property on the NFT, was originally the "contract" property before being repurposed to track the embeded NFT contracts.

we can add this definition back to the NFT under a two fold property: `Type` and `Main`
Type: "BlackMarket" or "Official"
Main: the contract origin hash ID, for BlackMarket this would be its own contract hash.

`Type` & `Main` should only be defined on Mint, it cannot be changed after.

**Comment by RawichK** [comment]
Got you, I will update BH NFT to include `Type` and `Main` which can be defined only on Mint by get data from provided base58 properties.

**Comment by RawichK** [comment]
@digimbyte One more thing to clarify,
I will change the method parameters like this attached image.
Please also help update the documentation. [https://docs.google.com/document/d/1eAPkjm8u2iRulE1vWdiCtV2LUF1MGjWgct1JA7B0q58](url)
![image](https://github.com/battlehard/hardened/assets/8307015/77c4beb9-7ab0-4e12-afd3-6c1920ca7b5b)
